# Pull official base image for RabbitMQ.
FROM rabbitmq:3-management

# Set local time as Sao Paulo in the container.
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone