# Geospacial database with PostGIS extensions.
FROM kartoza/postgis:13.0

# Set local time as Sao Paulo in the container.
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone